from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.db.models import Q
import datetime
import json
from teamScheduling.models import *
from django.core import serializers

# Create your views here.

def teams(request):
	ts = Team.objects.all()
	return render(request, 'teamScheduling/teams.html',
			{'teams':ts})
	
def team(request,teamId):
	players = Player.objects.filter(team__id=teamId)
	team    = Team.objects.get(id=teamId)
	games   = Game.objects.filter(Q(teamA=team) |
			Q(teamB=team)).order_by('time')
	for game in games:
		if game.teamA == team:
			game.opponent = game.teamB
		else:
			game.opponent = game.teamA
	return render(request, 'teamScheduling/team.html',
			{'players':players, 
				'team':team,
				'games':games,
			})

def subs(request,teamId,gameId):
	players = Player.objects.filter(team__id=teamId)
	team   = Team.objects.get(id=teamId)
	game   = Game.objects.get(id=gameId)
	params = request.GET.copy()
	params = dict(params.iterlists())
	subs = []
	if 'mp' in params:
		mps = Player.objects.filter(id__in=
				[int(f) for f in params['mp']])
		for player in players:
			if player.id in [int(f) for f in params['mp']]:
				player.selected = True
		subs = getSubs(game, mps)
	if game.teamA == team:
		game.opponent = game.teamB
	else:
		game.opponent = game.teamA
	return render(request, 'teamScheduling/subs.html',
			{'players':players, 
				'team':team,
				'game':game,
				'subs':subs,
			})


def apiTeams(request):
	ts = Team.objects.all()
	teams_json = serializers.serialize('json',ts)
	return HttpResponse(json.dumps(teams_json),
			content_type='application/json')
	
def apiGames(request):
	games = Game.objects.all()
	games_json = serializers.serialize('json',games)
	return HttpResponse(json.dumps(games_json),
			content_type='application/json')

def apiPlayers(request, teamId):
	ps = getPlayers(teamId) 
	ps_json = serializers.serialize('json',ps)
	return HttpResponse(json.dumps(ps_json),
			content_type='application/json')

def apiSubstitutes(request, gameId):
	game = Game.objects.get(id=gameId)
	list_mps = []
	params = request.GET.copy()
	params = dict(params.iterlists())
	mps = Player.objects.filter(id__in=
			[int(f) for f in params['mp']])
	subs = getSubs(game, mps)
	print "SUBS", subs
	subs_json = {}
	for i in subs:
		subs_json[i] = serializers.serialize('json',subs[i]) 
	return HttpResponse(json.dumps(subs_json),
			content_type='application/json')
@csrf_exempt
def apiGetSubList(request, teamId, gameId):
	players = Player.objects.filter(team__id=teamId)
	team   = Team.objects.get(id=teamId)
	game   = Game.objects.get(id=gameId)
	params = request.GET.copy()
	params = dict(params.iterlists())
	subs = []
	if 'mp' in params:
		mps = Player.objects.filter(id__in=
				[int(f) for f in params['mp']])
		subs = getSubs(game, mps)
		serialSubs = {}
		for r, subArr in subs.iteritems():
			serialSubs[r] = []
			for sub in subArr:
				serialSubs[r].append({
					'name': getPlayerName(sub),
					'email': sub.user.email,
				})
		ratings = {}
		for mp in mps:
			r = str(mp.rating)
			if r in ratings:
				ratings[r].append(getPlayerName(mp))
			else:
				ratings[r] = [getPlayerName(mp),]
		serialOut = {
			'rating_match': ratings,
			'subs': serialSubs,
		}

	return HttpResponse(json.dumps(serialOut),
			content_type='application/json')

MESSAGE_HEAD='''
Note: This is an automated email generated by the Arctic Coliseum

Dear valued Arctic Coliseum hockey player,
	 We are running short on players for ((this_game)) and
((this_coach)) is contacting you to see if you'd like to play at
((this_time)) for ((this_team))? Please reply to him if you'd like to
play.'''

MESSAGE_FOOT='''
This was a partially automated message from the Arctic Coliseum
'''
#TODO: Incorporate the actual game, team and captain info
def apiGetMessageInfo(request):
	ps = {
			'head':MESSAGE_HEAD,
			'foot':MESSAGE_FOOT
	}
	return HttpResponse(json.dumps(ps),
			content_type='application/json')

